### ISSUE TITLE
Register listeners not exist

### ISSUE THREAD

**Issue by sajadmartiny** [ajgarn/mpeventbus#1]
hi . i can not mpEventBus.register(this); in my fragment because not exist register method .
Thanks for library

**Comment by ajgarn** [comment]
Have you set your mpEventBus variable before you register?

MPEventBus mpEventBus = MPEventBus.getDefault();
mpEventBus.register(this);

**Comment by sajadmartiny** [comment]
yes

**Comment by ajgarn** [comment]
Sorry, I forgot to add the method to my event bus wrapper. It is now added.

Thank you!

**Comment by sajadmartiny** [comment]
Thank you
